-- ============================================================
-- РЕЕСТР ПОЛЕЙ: маппинг всех полей из CSV в таблицы БД
-- ============================================================

INSERT INTO field_registry (field_code, section_code, section_name, field_name, org_type_code, db_table, db_column) VALUES

-- ═══════════════ ОБЩИЕ СВЕДЕНИЯ ════════════════
('01','00','Общие сведения','ID системы учёта',                     'ДО',    'organizations','system_account_id'),
('01','00','Общие сведения','ID системы учёта',                     'ДопО',  'organizations','system_account_id'),
('01','00','Общие сведения','ID системы учёта',                     'СО',    'organizations','system_account_id'),
('01','00','Общие сведения','ID системы учёта',                     'ТиППО', 'organizations','system_account_id'),
('01','00','Общие сведения','ID системы учёта',                     'ВиПО',  'organizations','system_account_id'),
('01','00','Общие сведения','ID системы учёта',                     'Общ-е', 'organizations','system_account_id'),

('02','00','Общие сведения','БИН организации',                      'ДО',    'organizations','bin'),
('02','00','Общие сведения','БИН организации',                      'ДопО',  'organizations','bin'),
('02','00','Общие сведения','БИН организации',                      'СО',    'organizations','bin'),
('02','00','Общие сведения','БИН организации',                      'ТиППО', 'organizations','bin'),
('02','00','Общие сведения','БИН организации',                      'ВиПО',  'organizations','bin'),
('02','00','Общие сведения','БИН организации',                      'Общ-е', 'organizations','bin'),
('02','00','Общие сведения','БИН организации',                      'ГОНС',  'gons_institutions','bin'),

('03','00','Общие сведения','Наименование организации',             'ДО',    'organizations','name_ru'),
('03','00','Общие сведения','Наименование организации',             'ДопО',  'organizations','name_ru'),
('03','00','Общие сведения','Наименование организации',             'СО',    'organizations','name_ru'),
('03','00','Общие сведения','Наименование организации',             'ТиППО', 'organizations','name_ru'),
('03','00','Общие сведения','Наименование организации',             'ВиПО',  'organizations','name_ru'),
('03','00','Общие сведения','Наименование организации',             'Общ-е', 'organizations','name_ru'),

('04','00','Общие сведения','Форма собственности',                  'ДО',    'organizations','ownership_form_id'),
('04','00','Общие сведения','Форма собственности',                  'ДопО',  'organizations','ownership_form_id'),
('04','00','Общие сведения','Форма собственности',                  'СО',    'organizations','ownership_form_id'),
('04','00','Общие сведения','Форма собственности',                  'ТиППО', 'organizations','ownership_form_id'),
('04','00','Общие сведения','Форма собственности',                  'ВиПО',  'organizations','ownership_form_id'),
('04','00','Общие сведения','Форма собственности',                  'Общ-е', 'organizations','ownership_form_id'),

('05','00','Общие сведения','Область / город респ. значения',       'ДО',    'organizations','region_id'),
('05','00','Общие сведения','Область / город респ. значения',       'ДопО',  'organizations','region_id'),
('05','00','Общие сведения','Область / город респ. значения',       'СО',    'organizations','region_id'),
('05','00','Общие сведения','Область / город респ. значения',       'ТиППО', 'organizations','region_id'),
('05','00','Общие сведения','Область / город респ. значения',       'ВиПО',  'organizations','region_id'),
('05','00','Общие сведения','Область / город респ. значения',       'Общ-е', 'organizations','region_id'),
('05','00','Общие сведения','Область / город респ. значения',       'ГОНС',  'organizations','region_id'),

('06','00','Общие сведения','Населённый пункт и адрес',             'ДО',    'organizations','address_full'),
('06','00','Общие сведения','Населённый пункт и адрес',             'ДопО',  'organizations','address_full'),
('06','00','Общие сведения','Населённый пункт и адрес',             'СО',    'organizations','address_full'),
('06','00','Общие сведения','Населённый пункт и адрес',             'ТиППО', 'organizations','address_full'),
('06','00','Общие сведения','Населённый пункт и адрес',             'ВиПО',  'organizations','address_full'),
('06','00','Общие сведения','Населённый пункт и адрес',             'Общ-е', 'organizations','address_full'),

('07','00','Общие сведения','Лицензирование',                       'ДО',    'licenses','license_number'),
('07','00','Общие сведения','Лицензирование',                       'ДопО',  'licenses','license_number'),
('07','00','Общие сведения','Лицензирование',                       'СО',    'licenses','license_number'),
('07','00','Общие сведения','Лицензирование',                       'ТиППО', 'licenses','license_number'),
('07','00','Общие сведения','Лицензирование',                       'ВиПО',  'licenses','license_number'),

('08','00','Общие сведения','Дата получения лицензии',              'СО',    'licenses','issue_date'),
('08','00','Общие сведения','Дата получения лицензии',              'ТиППО', 'licenses','issue_date'),
('08','00','Общие сведения','Дата получения лицензии',              'ВиПО',  'licenses','issue_date'),
('08','00','Общие сведения','Дата получения лицензии',              'ГОНС',  'gons_institutions','license_date'),

('09','00','Общие сведения','Аккредитация',                         'ТиППО', 'accreditations','accred_body'),
('09','00','Общие сведения','Аккредитация',                         'ВиПО',  'accreditations','accred_body'),

('10','00','Общие сведения','Количество организаций (созданных, действующих, ликвидированных)', 'ДО',   'organizations','status'),
('10','00','Общие сведения','Количество организаций',               'ДопО',  'organizations','status'),
('10','00','Общие сведения','Количество организаций',               'СО',    'organizations','status'),
('10','00','Общие сведения','Количество организаций',               'ТиППО', 'organizations','status'),
('10','00','Общие сведения','Количество организаций',               'ВиПО',  'organizations','status'),

('11','00','Общие сведения','Вид организации образования',          'ДО',    'organizations','org_kind_id'),
('11','00','Общие сведения','Вид организации образования',          'ДопО',  'organizations','org_kind_id'),
('11','00','Общие сведения','Вид организации образования',          'СО',    'organizations','org_kind_id'),
('11','00','Общие сведения','Вид организации образования',          'ТиППО', 'organizations','org_kind_id'),
('11','00','Общие сведения','Вид организации образования',          'ВиПО',  'organizations','org_kind_id'),
('11','00','Общие сведения','Вид организации образования',          'Общ-е', 'organizations','org_kind_id'),

('12','00','Общие сведения','Начало образовательной деятельности',  'ДО',    'organizations','activity_start_date'),
('12','00','Общие сведения','Начало образовательной деятельности',  'ДопО',  'organizations','activity_start_date'),
('12','00','Общие сведения','Начало образовательной деятельности',  'СО',    'organizations','activity_start_date'),
('12','00','Общие сведения','Начало образовательной деятельности',  'ТиППО', 'organizations','activity_start_date'),
('12','00','Общие сведения','Начало образовательной деятельности',  'ВиПО',  'organizations','activity_start_date'),

('13','00','Общие сведения','Дата реорганизации/переучреждения',    'ДО',    'organizations','reorganization_date'),
('13','00','Общие сведения','Дата реорганизации/переучреждения',    'ДопО',  'organizations','reorganization_date'),
('13','00','Общие сведения','Дата реорганизации/переучреждения',    'СО',    'organizations','reorganization_date'),
('13','00','Общие сведения','Дата реорганизации/переучреждения',    'ТиППО', 'organizations','reorganization_date'),
('13','00','Общие сведения','Дата реорганизации/переучреждения',    'ВиПО',  'organizations','reorganization_date'),

('14','00','Общие сведения','Направления подготовки',               'ТиППО', 'training_directions','ugse_name'),
('14','00','Общие сведения','Направления подготовки',               'ВиПО',  'training_directions','ugse_name'),

('15','00','Общие сведения','Статус (нац./гос./рег./частн./межд.)', 'ВиПО',  'organizations','vuz_status'),

('16','00','Общие сведения','Планы развития, стратегические планы', 'ДО',    'org_strategic_docs','title'),
('16','00','Общие сведения','Планы развития, стратегические планы', 'ДопО',  'org_strategic_docs','title'),
('16','00','Общие сведения','Планы развития, стратегические планы', 'СО',    'org_strategic_docs','title'),
('16','00','Общие сведения','Планы развития, стратегические планы', 'ТиППО', 'org_strategic_docs','title'),
('16','00','Общие сведения','Планы развития, стратегические планы', 'ВиПО',  'org_strategic_docs','title'),

('17','00','Общие сведения','Заявления на присоединение поставщиков','ДО',   'org_contracts','contract_type'),
('17','00','Общие сведения','Заявления на присоединение поставщиков','ДопО', 'org_contracts','contract_type'),
('17','00','Общие сведения','Заявления на присоединение поставщиков','СО',   'org_contracts','contract_type'),

('18','00','Общие сведения','Договоры поручения/присоединения',     'ДО',    'org_contracts','contract_type'),
('18','00','Общие сведения','Договоры поручения/присоединения',     'ДопО',  'org_contracts','contract_type'),
('18','00','Общие сведения','Договоры поручения/присоединения',     'СО',    'org_contracts','contract_type'),
('18','00','Общие сведения','Договоры поручения/присоединения',     'ТиППО', 'org_contracts','contract_type'),
('18','00','Общие сведения','Договоры поручения/присоединения',     'ВиПО',  'org_contracts','contract_type'),

-- ═══════════════ КОНТИНГЕНТ ════════════════
('01','01','Контингент','Общая численность',                        'ДО',    'contingent_snapshots','total_count'),
('01','01','Контингент','Общая численность',                        'ДопО',  'contingent_snapshots','total_count'),
('01','01','Контингент','Общая численность',                        'СО',    'contingent_snapshots','total_count'),
('01','01','Контингент','Общая численность',                        'ТиППО', 'contingent_snapshots','total_count'),
('01','01','Контингент','Общая численность',                        'ВиПО',  'contingent_snapshots','total_count'),

('02','01','Контингент','Численность по языку обучения',            'ДО',    'contingent_snapshots','kz_lang_count'),
('03','01','Контингент','Вновь принятые',                           'ДО',    'contingent_snapshots','new_enrolled'),
('04','01','Контингент','Многодетные/малообеспеч./инвалиды/сироты', 'ДО',    'contingent_snapshots','many_children_count'),
('05','01','Контингент','Дети с ООП',                               'ДО',    'contingent_snapshots','oop_count'),
('06','01','Контингент','Иностранцы',                               'ДО',    'contingent_snapshots','foreign_count'),
('07','01','Контингент','Призёры олимпиад',                         'ДопО',  'contingent_snapshots','prize_winners_json'),
('08','01','Контингент','Проживают в интернате',                    'СО',    'contingent_snapshots','boarding_school_count'),
('09','01','Контингент','По специальностям/направлениям/годам',     'ТиППО', 'contingent_snapshots','by_specialty_json'),
('10','01','Контингент','По возрастным группам',                    'ДО',    'contingent_snapshots','by_grade_json'),
('11','01','Контингент','Бакалавр/Магистр/PhD; очно/дист.; бюд./плат.','ВиПО','contingent_snapshots','bachelor_count'),
('12','01','Контингент','Доля льготников',                          'ДО',    'contingent_snapshots','privileged_share'),
('13','01','Контингент','По направлениям STEM/мед./пед.',           'ТиППО', 'contingent_snapshots','by_specialty_json'),
('15','01','Контингент','Доля дуального обучения',                  'ТиППО', 'contingent_snapshots','total_count'),
('16','01','Контингент','Приток и отток студентов',                 'ТиППО', 'enrollment_records','action'),
('17','01','Контингент','Дата зачисления',                          'ДО',    'enrollment_records','action_date'),
('18','01','Контингент','Дата отчисления',                          'ДО',    'enrollment_records','action_date'),
('19','01','Контингент','Численность отчисленных',                  'ДО',    'contingent_snapshots','withdrawn'),
('20','01','Контингент','Информация по очереди',                    'ДО',    'queue_records','queue_count'),
('21','01','Контингент','Табели посещаемости',                      'ДО',    'attendance_records','present_count'),
('22','01','Контингент','Количество пропусков',                     'ДО',    'attendance_records','absent_count'),
('23','01','Контингент','Подали заявки на общежитие',               'ТиППО', 'dormitory_applications','applied_count'),
('24','01','Контингент','Заявки на общежитие: удовлетворены/отказаны','ТиППО','dormitory_applications','approved_count'),
('25','01','Контингент','В каком общежитии зарегистрированы',       'ТиППО', 'dormitory_residents','dormitory_id'),
('26','01','Контингент','С какого периода проживают',               'ТиППО', 'dormitory_residents','check_in_date'),

-- ГОНС контингент
('27','01','Контингент','Вкладчики/выгодоприобрет. в рамках ГОНС',  'ГОНС',  'gons_beneficiaries_snapshot','total_count'),
('28','01','Контингент','По возрастам',                             'ГОНС',  'gons_beneficiaries_snapshot','by_age_json'),
('29','01','Контингент','Категории СУСН',                           'ГОНС',  'gons_beneficiaries_snapshot','susn_disabled_count'),
('30','01','Контингент','Дети-сироты',                              'ГОНС',  'gons_beneficiaries_snapshot','orphans_count'),
('31','01','Контингент','Направили на образование',                 'ГОНС',  'gons_beneficiaries_snapshot','directed_to_education_count'),
('32','01','Контингент','Направили на жильё',                       'ГОНС',  'gons_beneficiaries_snapshot','directed_to_housing_count'),
('33','01','Контингент','Перевели из БВУ в БВУ и т.д.',             'ГОНС',  'gons_beneficiaries_snapshot','transferred_between_count'),
('34','01','Контингент','Перевели в пользу третьего лица',          'ГОНС',  'gons_beneficiaries_snapshot','transferred_to_third_count'),
('35','01','Контингент','Нацфонд-детям объединили',                 'ГОНС',  'gons_beneficiaries_snapshot','natsfond_combined_count'),

-- ═══════════════ ГРУППЫ ════════════════
('01','02','Группы','Виды групп',                                   'ДО',    'groups','group_type'),
('02','02','Группы','Виды кружков/секций',                          'ДО',    'groups','circle_section_type'),
('03','02','Группы','Количество групп',                             'ДО',    'groups','id'),
('07','02','Группы','Инклюзивные/специальные/с ООП',               'ДО',    'groups','group_type'),
('08','02','Группы','Наполняемость групп',                          'ДО',    'groups','capacity'),

-- ═══════════════ ПЕДСОСТАВ ════════════════
('11','03','Педсостав','Штатное расписание',                        'ДО',    'staff_snapshots','staffing_plan_json'),
('01','03','Педсостав','Численность педагогов/мастеров ПО',         'ДО',    'staff_snapshots','total_teachers'),
('02','03','Педсостав','Дефектологи/логопеды/психологи',            'ДО',    'staff_snapshots','spec_teachers_count'),
('03','03','Педсостав','Прошли повышение квалификации',             'ДО',    'staff_snapshots','trained_count'),
('04','03','Педсостав','Прошли аттестацию',                        'ДО',    'staff_snapshots','certified_count'),
('05','03','Педсостав','Внешние экзаменаторы',                      'ТиППО', 'staff_snapshots','external_examiners'),
('06','03','Педсостав','Участвуют в проф. конкурсах',               'ДО',    'staff_snapshots','contest_participants'),
('07','03','Педсостав','Результаты участия в конкурсах',            'ДО',    'staff_snapshots','contest_results_json'),
('08','03','Педсостав','Категория/степень педагогов',               'ДО',    'staff_snapshots','qualification_json'),
('09','03','Педсостав','Кадры с производства',                      'ТиППО', 'staff_snapshots','production_staff_count'),
('12','03','Педсостав','Уровень нагрузки педагогов',                'ДО',    'staff_snapshots','avg_workload_hours'),
('13','03','Педсостав','Текучесть кадров',                          'ДО',    'staff_snapshots','turnover_rate'),
('14','03','Педсостав','Укомплектованность кадрами',                'ДО',    'staff_snapshots','staffing_rate'),
('15','03','Педсостав','Средний опыт работы',                       'ДО',    'staff_snapshots','avg_experience_years'),
('16','03','Педсостав','Соотношение педагог/дети',                  'ДО',    'staff_snapshots','teacher_child_ratio'),

-- ═══════════════ ФИНАНСЫ ════════════════
('01','04','Финансы','Источники финансирования',                    'ДО',    'finance_records','funding_sources_json'),
('02','04','Финансы','Годовой бюджет учреждения',                   'ДО',    'finance_records','annual_budget'),
('03','04','Финансы','Объём средств на госзаказ',                   'ДО',    'finance_records','state_order_volume'),
('04','04','Финансы','Заявки на финансирование',                    'ДО',    'finance_records','financing_requests_count'),
('05','04','Финансы','Затраты по спецификам и видам',               'ДО',    'finance_records','funding_sources_json'),
('06','04','Финансы','Подушевой/базовый норматив',                  'ДО',    'finance_records','per_capita_norm'),
('07','04','Финансы','Срок размещения госзаказа',                   'ДО',    'finance_records','state_order_start_date'),
('08','04','Финансы','Информация о нарушениях и штрафах',           'ДО',    'finance_records','violations_info'),
('12','04','Финансы','Количество выданных ваучеров',                'ДО',    'finance_records','vouchers_issued'),
('13','04','Финансы','Сумма оплат поставщикам',                     'ДО',    'finance_records','payments_to_suppliers'),
('14','04','Финансы','Стоимость кружка за занятие',                 'ДО',    'finance_records','circle_price_per_session'),
('20','04','Финансы','Объём внебюджетных доходов',                  'ДО',    'finance_records','extra_budget_income'),
('22','04','Финансы','Расходы на ЖКУ/ремонт/МТБ',                  'ДО',    'finance_records','expenses_utilities'),
('23','04','Финансы','Расходы на ФОТ',                              'ДО',    'finance_records','expenses_payroll'),
('25','04','Финансы','Расходы на питание',                          'ДО',    'finance_records','expenses_food'),
('26','04','Финансы','Расходы на медобслуживание',                  'ДО',    'finance_records','expenses_medical'),
('27','04','Финансы','Расходы на переквалификацию',                 'ДО',    'finance_records','expenses_retraining'),
('28','04','Финансы','Расходы на олимпиады/конкурсы',               'ДО',    'finance_records','expenses_olympiads'),
('32','04','Финансы','Расходы на НИОКР',                            'ВиПО',  'finance_records','expenses_rnd'),
('33','04','Финансы','Расходы на стипендии',                        'ВиПО',  'finance_records','expenses_scholarships'),
('34','04','Финансы','Расходы на содержание интерната',             'СО',    'finance_records','expenses_boarding'),
-- ГОНС финансы
('35','04','Финансы','Общая сумма вкладов Aqyl',                    'ГОНС',  'gons_daily_snapshot','deposits_aquyl_total_amount'),
('36','04','Финансы','Общая сумма страховых премий',                'ГОНС',  'gons_daily_snapshot','insurance_premiums_total'),
('37','04','Финансы','Общая сумма премии государства',              'ГОНС',  'gons_daily_snapshot','state_bonus_total'),
('38','04','Финансы','Общая сумма СОК',                             'ГОНС',  'gons_daily_snapshot','sok_total'),

-- ═══════════════ ОБОРУДОВАНИЕ ════════════════
('01','05','Оборудование','МТБ',                                    'ДО',    'equipment_records','mtb_general_json'),
('02','05','Оборудование','МТБ для спецгрупп',                      'ДО',    'equipment_records','mtb_special_groups_json'),
('03','05','Оборудование','Учебные материалы (библиотека, ЭУ)',      'ДО',    'equipment_records','e_textbooks_count'),
('04','05','Оборудование','Амортизация оборудования',               'ДО',    'equipment_records','wear_pct'),
('05','05','Оборудование','Расходные материалы (реактивы)',          'ТиППО', 'equipment_records','consumables_json'),
('06','05','Оборудование','Расходные материалы для практики',        'ТиППО', 'equipment_records','practice_consumables_annual'),
('07','05','Оборудование','Производственные мастерские',             'ТиППО', 'equipment_records','production_workshops_json'),
('08','05','Оборудование','Научное оборудование',                   'ВиПО',  'equipment_records','science_equipment_json'),
('09','05','Оборудование','IT-оборудование (серверы, ПК, симул.)',   'ТиППО', 'equipment_records','computers_count'),
('10','05','Оборудование','Инвестиции в оборудование за 3 года',     'ТиППО', 'equipment_records','investments_3y_json'),

-- ═══════════════ ИНФРАСТРУКТУРА ════════════════
('01','06','Инфраструктура','Тип здания',                           'ДО',    'infrastructure_records','building_type'),
('02','06','Инфраструктура','Техническое состояние',                'ДО',    'infrastructure_records','technical_condition'),
('03','06','Инфраструктура','Проектная мощность',                   'ДО',    'infrastructure_records','design_capacity'),
('04','06','Инфраструктура','Площадь здания',                       'ДО',    'infrastructure_records','building_area_sqm'),
('05','06','Инфраструктура','Общая площадь территории',             'ДО',    'infrastructure_records','total_territory_sqm'),
('06','06','Инфраструктура','Год постройки и ввода',                'ДО',    'infrastructure_records','construction_year'),
('07','06','Инфраструктура','Состояние/износ здания',               'ДО',    'infrastructure_records','building_condition_wear_pct'),
('08','06','Инфраструктура','Дата ремонта',                         'ДО',    'infrastructure_records','last_repair_date'),
('09','06','Инфраструктура','Соответствие нормам СанПин',           'ДО',    'infrastructure_records','sanpin_compliance'),
('10','06','Инфраструктура','Вид отопления',                        'ДО',    'infrastructure_records','heating_type'),
('11','06','Инфраструктура','Количество корпусов',                  'ДО',    'infrastructure_records','building_count'),
('12','06','Инфраструктура','Антитеррористическая безопасность',    'ДО',    'infrastructure_records','antiterror_security'),
('13','06','Инфраструктура','Собственное/арендуемое помещение',     'ДО',    'infrastructure_records','premises_ownership'),
('14','06','Инфраструктура','Транспортная доступность',             'ДО',    'infrastructure_records','transport_access'),
('15','06','Инфраструктура','Учебная инфраструктура',               'ДО',    'infrastructure_records','edu_infra_details_json'),
('16','06','Инфраструктура','Спортивная инфраструктура',            'ДО',    'infrastructure_records','sports_infra_json'),
('17','06','Инфраструктура','Наличие библиотеки',                   'ДО',    'infrastructure_records','has_library'),
('18','06','Инфраструктура','Наличие интернета',                    'ДО',    'infrastructure_records','has_internet'),
('19','06','Инфраструктура','Наличие столовой/буфета',              'ДО',    'infrastructure_records','has_canteen'),
('20','06','Инфраструктура','Наличие развозки',                     'ДО',    'infrastructure_records','has_shuttle'),

-- ═══════════════ ОБРАЗОВАТ. ПРОЦЕСС ════════════════
('01','07','Образоват. процесс','Обязательные программы',           'ДО',    'educational_process','mandatory_programs_count'),
('02','07','Образоват. процесс','Международные программы',          'ДО',    'educational_process','international_programs_count'),
('03','07','Образоват. процесс','Программы по выбору',              'ДО',    'educational_process','optional_programs_count'),
('04','07','Образоват. процесс','Доп. виды программ',               'ДО',    'educational_process','additional_programs_json'),
('05','07','Образоват. процесс','Виды кружков/секций',              'ДО',    'educational_process','circles_sections_json'),
('06','07','Образоват. процесс','Развивающая среда',                'ДО',    'educational_process','has_developing_environment'),
('07','07','Образоват. процесс','Участие в олимпиадах',             'ДО',    'educational_process','olympiad_participation_json'),
('08','07','Образоват. процесс','Стартап-проекты',                  'ДО',    'educational_process','startup_projects_count'),
('09','07','Образоват. процесс','Опросы/анкетирование родителей',   'ДО',    'educational_process','parent_survey_results_json'),
('10','07','Образоват. процесс','Академическая мобильность',        'ВиПО',  'educational_process','academic_mobility_json'),
('11','07','Образоват. процесс','Академическая успеваемость',       'ВиПО',  'educational_process','academic_performance_json'),
('12','07','Образоват. процесс','Практика студентов',               'ВиПО',  'educational_process','practice_partners_json'),

-- ═══════════════ ВЫПУСКНИКИ ════════════════
('01','08','Выпускники','Численность выпускников',                  'СО',    'graduates_records','graduates_total'),
('02','08','Выпускники','Поступили в ТиППО',                        'СО',    'graduates_records','to_tippo_count'),
('03','08','Выпускники','Поступили в ВиПО',                         'СО',    'graduates_records','to_vipo_count'),
('04','08','Выпускники','Поступили в топовые ВиПО',                 'СО',    'graduates_records','to_top_vipo_count'),
('05','08','Выпускники','Не поступили',                             'СО',    'graduates_records','not_enrolled_count'),
('06','08','Выпускники','Результаты итоговой аттестации',           'СО',    'graduates_records','final_attestation_avg_score'),
('07','08','Выпускники','Доля трудоустроенных',                     'ТиППО', 'graduates_records','employed_6m_pct'),
('08','08','Выпускники','Средняя зарплата выпускников',             'ТиППО', 'graduates_records','avg_salary_by_specialty_json'),
('09','08','Выпускники','Достижения выпускников',                   'ТиППО', 'graduates_records','achievements_json'),
('10','08','Выпускники','Участие в юрлицах',                        'ТиППО', 'graduates_records','legal_entities_participation_json'),
('11','08','Выпускники','Выплаченные налоги',                       'ТиППО', 'graduates_records','taxes_paid_json'),
('12','08','Выпускники','Опросы выпускников',                       'ТиППО', 'graduates_records','survey_results_json'),
('13','08','Выпускники','Партнёры-работодатели',                    'ВиПО',  'graduates_records','employer_partners_json'),
('14','08','Выпускники','Отработка выпускников гранта',             'ВиПО',  'graduates_records','grant_workback_amount'),

-- ═══════════════ МЕЖДУНАРОДНАЯ ДЕЯТЕЛЬНОСТЬ ════════════════
('01','09','Международная','Иностранные студенты',                  'ТиППО', 'international_activity','foreign_students_count'),
('02','09','Международная','Иностранные преподаватели',             'ТиППО', 'international_activity','foreign_teachers_count'),
('03','09','Международная','Международные программы',               'ТиППО', 'international_activity','international_programs_json'),
('04','09','Международная','Партнёрские зарубежные вузы',           'ТиППО', 'international_activity','partner_universities_json'),

-- ═══════════════ НАУЧНАЯ ДЕЯТЕЛЬНОСТЬ ════════════════
('01','10','Наука','Научные гранты',                                'ВиПО',  'science_activity','grants_json'),
('02','10','Наука','Проекты студентов, стартапы',                   'ВиПО',  'science_activity','student_projects_json'),
('03','10','Наука','Индекс Хирша ППС',                              'ВиПО',  'science_activity','hirsch_index_avg'),
('04','10','Наука','Публикации Q1-Q4, Scopus, WoS',                 'ВиПО',  'science_activity','publications_scopus'),

-- ═══════════════ ЦИФРОВИЗАЦИЯ ════════════════
('01','11','Цифровизация','Наличие ИС',                             'ДО',    'digitalization_records','information_systems_json'),
('02','11','Цифровизация','Цифровые платформы/LMS',                  'ДО',    'digitalization_records','digital_platforms_json'),
('03','11','Цифровизация','Тех. защита (антивирус, ОС)',              'ДО',    'digitalization_records','tech_protection_json'),
('04','11','Цифровизация','Документы по ИБ и защите ПД',            'ДО',    'digitalization_records','infosec_docs_json'),
('05','11','Цифровизация','ERP/СУБД',                               'ДО',    'digitalization_records','erp_systems_json'),
('06','11','Цифровизация','Автосистема учёта (турникет/FaceID)',     'ДО',    'digitalization_records','auto_accounting_system'),
('07','11','Цифровизация','Сайт/мобильное приложение/е-библиотека', 'ДО',    'digitalization_records','has_website'),
('08','11','Цифровизация','Интернет: скорость, стабильность',        'ДО',    'digitalization_records','internet_speed_mbps'),
('09','11','Цифровизация','IT-оборудование',                        'ДО',    'digitalization_records','computers_count'),

-- ═══════════════ МЕДИЦИНА ════════════════
('01','12','Медицина','Медицинский кабинет',                        'ДО',    'medical_records','has_medical_office'),
('02','12','Медицина','Договор на мед. обслуживание',               'ДО',    'medical_records','has_medical_contract'),
('03','12','Медицина','Медперсонал (штат/факт)',                     'ДО',    'medical_records','medical_staff_actual'),
('04','12','Медицина','Медуслуги: осмотры, профилактика',           'ДО',    'medical_records','examinations_count'),
('05','12','Медицина','Охрана труда и ТБ',                          'ДО',    'medical_records','safety_briefing_journal'),

-- ═══════════════ АНТИФРОД ════════════════
('01','13','Мошенничество','Корректность ИИН воспитанника ДО',      'ДО',    'fraud_checks','check_type'),
('02','13','Мошенничество','Корректность ИИН ученика ОДО',          'ДопО',  'fraud_checks','check_type'),
('03','13','Мошенничество','Корректность ИИН ученика СО',           'СО',    'fraud_checks','check_type'),
('04','13','Мошенничество','Корректность ИИН студента ТиППО',       'ТиППО', 'fraud_checks','check_type'),
('05','13','Мошенничество','Корректность ИИН студента ВиПО',        'ВиПО',  'fraud_checks','check_type'),

-- ═══════════════ ОБЩЕЖИТИЯ - ОБЩИЕ СВЕДЕНИЯ ════════════════
('01','14','Общежития','Год постройки и ввод',                      'Общ-е', 'dormitories','construction_year'),
('02','14','Общежития','Общая площадь кв.м',                        'Общ-е', 'dormitories','area_total_sqm'),
('03','14','Общежития','Полезная площадь кв.м',                     'Общ-е', 'dormitories','area_useful_sqm'),
('04','14','Общежития','Площадь земельного участка',                 'Общ-е', 'dormitories','land_area_sqm'),
('05','14','Общежития','Вспомогательные помещения',                  'Общ-е', 'dormitories','auxiliary_rooms_json'),
('06','14','Общежития','Проектная мощность',                        'Общ-е', 'dormitories','design_capacity'),
('07','14','Общежития','Техническое состояние',                     'Общ-е', 'dormitories','technical_condition'),
('08','14','Общежития','Материал стен',                             'Общ-е', 'dormitories','wall_material'),
('09','14','Общежития','Количество этажей',                         'Общ-е', 'dormitories','floors_count'),
('10','14','Общежития','Дата капитального ремонта',                 'Общ-е', 'dormitories','last_capital_repair_date'),
('11','14','Общежития','Количество мест по проекту',                'Общ-е', 'dormitories','planned_capacity'),
('12','14','Общежития','Количество жилых комнат и площадь',         'Общ-е', 'dormitories','rooms_count'),

-- ═══════════════ МОНИТОРИНГ ПРОЖИВАНИЯ ════════════════
('01','15','Мониторинг общежитий','Фактически занятые места',       'Общ-е', 'dormitory_occupancy','occupied_places'),
('02','15','Мониторинг общежитий','Интеграция Студом/ЕПВО/ГБДФЛ',   'Общ-е', 'dormitory_residents','iin_verified_gbdfl'),
('03','15','Мониторинг общежитий','Проверка места обучения (НОБД)',  'Общ-е', 'dormitory_residents','study_place_verified'),
('04','15','Мониторинг общежитий','Проверка места обучения (ЕПВО)', 'Общ-е', 'dormitory_residents','study_place_verified'),
('05','15','Мониторинг общежитий','Проверка прописки ГБДФЛ',        'Общ-е', 'dormitory_residents','residence_verified'),
('06','15','Мониторинг общежитий','Корректность ИИН студента',      'Общ-е', 'dormitory_residents','iin_verified_gbdfl'),
('07','15','Мониторинг общежитий','Часы проживания в месяц',        'Общ-е', 'dormitory_residents','monthly_stay_hours'),
('08','15','Мониторинг общежитий','Фиксация периода проживания',    'Общ-е', 'dormitory_residents','check_in_date'),
('09','15','Мониторинг общежитий','Формирование реестра',           'Общ-е', 'dormitory_residents','registry_correct'),

-- ═══════════════ ЭТАПЫ ЗАЯВЛЕНИЙ ПОСТАВЩИКОВ ════════════════
('01','16','Этапы поставщиков','Подача заявления и документов',     'Общ-е', 'dormitory_supplier_contracts','application_date'),
('05','16','Этапы поставщиков','Заключение предварит. договора',    'Общ-е', 'dormitory_supplier_contracts','prelim_contract_date'),
('06','16','Этапы поставщиков','Соглашение о неизменности назнач.', 'Общ-е', 'dormitory_supplier_contracts','target_agreement_date'),
('07','16','Этапы поставщиков','Доп. соглашение к предв. договору', 'Общ-е', 'dormitory_supplier_contracts','addendum_date'),
('08','16','Этапы поставщиков','Заключение договора госзаказа',     'Общ-е', 'dormitory_supplier_contracts','state_order_contract_date'),
('09','16','Этапы поставщиков','Срок договора госзаказа',           'Общ-е', 'dormitory_supplier_contracts','state_order_contract_period'),
('10','16','Этапы поставщиков','Мониторинг ввода объекта',          'Общ-е', 'dormitory_supplier_contracts','status'),
('11','16','Этапы поставщиков','Ввод объекта в эксплуатацию',       'Общ-е', 'dormitory_supplier_contracts','commissioning_date'),
('12','16','Этапы поставщиков','Расторжение предв. договора',       'Общ-е', 'dormitory_supplier_contracts','termination_prelim_date'),
('13','16','Этапы поставщиков','Расторжение договора госзаказа',    'Общ-е', 'dormitory_supplier_contracts','termination_contract_date');
