"""
models/organization.py
─────────────────────────────────────────────────────────────────────────────
ORM models for core lookup + organisation tables.

These models are imported by Alembic migrations (autogenerate) and by
the CRUD / service layers.  All reference tables (org_types, regions, etc.)
are defined here to keep the dependency graph simple.

Column names match edu_monitoring_schema.sql exactly.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Optional
from uuid import UUID

from sqlalchemy import (
    Boolean, CheckConstraint, Date, DateTime, ForeignKey,
    Index, Integer, String, Text, UniqueConstraint, func,
)
from sqlalchemy.dialects.postgresql import ARRAY, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


# ─────────────────────────────────────────────────────────────────────────────
# Lookup / reference tables
# ─────────────────────────────────────────────────────────────────────────────

class OrgType(Base):
    """Типы образовательных организаций: ДО, ДопО, СО, ТиППО, ВиПО, Общ-е, ГОНС"""
    __tablename__ = "org_types"

    id:          Mapped[int]           = mapped_column(Integer, primary_key=True)
    code:        Mapped[str]           = mapped_column(String(20), unique=True, nullable=False)
    name_ru:     Mapped[str]           = mapped_column(Text, nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)


class Region(Base):
    """Регионы: области + города республиканского значения"""
    __tablename__ = "regions"

    id:      Mapped[int]           = mapped_column(Integer, primary_key=True)
    code:    Mapped[str]           = mapped_column(String(10), unique=True, nullable=False)
    name_ru: Mapped[str]           = mapped_column(Text, nullable=False)
    type:    Mapped[Optional[str]] = mapped_column(
        String(20),
        CheckConstraint("type IN ('oblast','city')", name="ck_region_type"),
    )
    localities: Mapped[list["Locality"]] = relationship(
        back_populates="region", lazy="noload"
    )


class Locality(Base):
    """Населённые пункты — город, село, пгт"""
    __tablename__ = "localities"
    __table_args__ = (
        UniqueConstraint("region_id", "name_ru", name="uq_locality_region_name"),
    )

    id:        Mapped[int]           = mapped_column(Integer, primary_key=True)
    region_id: Mapped[int]           = mapped_column(
        Integer, ForeignKey("regions.id"), nullable=False
    )
    name_ru:   Mapped[str]           = mapped_column(Text, nullable=False)
    type:      Mapped[Optional[str]] = mapped_column(String(30))

    region: Mapped["Region"] = relationship(back_populates="localities", lazy="noload")


class OwnershipForm(Base):
    """Формы собственности: Государственная, Частная, ГЧП, Коммунальная..."""
    __tablename__ = "ownership_forms"

    id:      Mapped[int] = mapped_column(Integer, primary_key=True)
    code:    Mapped[str] = mapped_column(String(20), unique=True, nullable=False)
    name_ru: Mapped[str] = mapped_column(Text, nullable=False)


class OrgKind(Base):
    """Виды организаций: мини-центр, полного дня, спортивная школа..."""
    __tablename__ = "org_kinds"

    id:          Mapped[int]           = mapped_column(Integer, primary_key=True)
    org_type_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("org_types.id"), nullable=True
    )
    name_ru:     Mapped[str]           = mapped_column(Text, nullable=False)


class DataSource(Base):
    """Источники данных: НОБД, ЕПВО, eGov, Кунделик..."""
    __tablename__ = "data_sources"

    id:      Mapped[int]           = mapped_column(Integer, primary_key=True)
    code:    Mapped[str]           = mapped_column(String(50), unique=True, nullable=False)
    name_ru: Mapped[str]           = mapped_column(Text, nullable=False)
    url:     Mapped[Optional[str]] = mapped_column(Text)


# ─────────────────────────────────────────────────────────────────────────────
# Core: Organization
# ─────────────────────────────────────────────────────────────────────────────

class Organization(Base):
    """
    Центральная таблица — все образовательные организации.
    UUID PK (not autoincrement) for distributed-safe insertion.
    """
    __tablename__ = "organizations"
    __table_args__ = (
        CheckConstraint(
            "status IN ('active','reorganized','liquidated')",
            name="ck_org_status",
        ),
        Index("ix_org_type_id",  "org_type_id"),
        Index("ix_org_bin",      "bin",       unique=True),
        Index("ix_org_region_id","region_id"),
        Index("ix_org_status",   "status"),
    )

    # ── PK (UUID generated by PostgreSQL uuid_generate_v4()) ──────────────
    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.uuid_generate_v4(),
        comment="UUID — generated by PostgreSQL",
    )

    # ── Identity ──────────────────────────────────────────────────────────
    system_account_id: Mapped[Optional[str]] = mapped_column(
        Text, comment="ID системы учёта (01)"
    )
    bin: Mapped[Optional[str]] = mapped_column(
        String(12), unique=True, comment="БИН организации (02)"
    )
    name_ru: Mapped[str] = mapped_column(
        Text, nullable=False, comment="Полное наименование (03)"
    )

    # ── FK references ─────────────────────────────────────────────────────
    org_type_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("org_types.id")
    )
    org_kind_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("org_kinds.id")
    )
    ownership_form_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("ownership_forms.id")
    )
    region_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("regions.id")
    )
    locality_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("localities.id")
    )

    # ── Location ──────────────────────────────────────────────────────────
    address_full: Mapped[Optional[str]] = mapped_column(Text)

    # ── Activity ──────────────────────────────────────────────────────────
    activity_start_date: Mapped[Optional[date]] = mapped_column(Date)
    reorganization_date: Mapped[Optional[date]] = mapped_column(Date)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="active"
    )

    # ── ВиПО specific ─────────────────────────────────────────────────────
    vuz_status: Mapped[Optional[str]] = mapped_column(
        String(30), comment="национальный / государственный / ..."
    )

    # ── Timestamps ────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # ── Relationships (lazy="noload" — must be explicit in async code) ─────
    org_type: Mapped[Optional["OrgType"]] = relationship(lazy="noload")
    region:   Mapped[Optional["Region"]]   = relationship(lazy="noload")


# ─────────────────────────────────────────────────────────────────────────────
# API tokens table (for machine-to-machine access)
# ─────────────────────────────────────────────────────────────────────────────

class ApiToken(Base):
    """
    API tokens — stores bcrypt-hashed token values.
    Scopes: TEXT[] PostgreSQL array — ['read'], ['read','write'], etc.
    """
    __tablename__ = "api_tokens"

    id:           Mapped[int]           = mapped_column(Integer, primary_key=True)
    token_hash:   Mapped[str]           = mapped_column(Text, unique=True, nullable=False)
    org_id:       Mapped[Optional[UUID]] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("organizations.id")
    )
    name:         Mapped[Optional[str]] = mapped_column(Text)
    scopes:       Mapped[Optional[list[str]]] = mapped_column(ARRAY(Text))
    is_active:    Mapped[bool]          = mapped_column(Boolean, default=True)
    created_at:   Mapped[datetime]      = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    expires_at:   Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    last_used_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
