"""
models/user.py
─────────────────────────────────────────────────────────────────────────────
Native User model.  Stores bcrypt-hashed passwords — no external auth provider.

Columns:
    id                UUID (generated by PostgreSQL)
    email             Unique, indexed, lowercase-normalised
    password_hash     bcrypt hash (60 chars)
    full_name         Display name
    role              RBAC role: superadmin / admin / management / data_entry
    org_id            FK to organizations (NULL for admin/superadmin)
    is_active         Account enabled flag
    last_login_at     Timestamp of most recent successful login
    failed_attempts   Counter for brute-force protection
    locked_until      Lockout timestamp (if too many failed attempts)
    must_change_pwd   True on first login after admin creates / resets password
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional
from uuid import UUID

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class UserRoleEnum:
    """Single source of truth for role string values."""
    SUPERADMIN = "superadmin"
    ADMIN      = "admin"
    MANAGEMENT = "management"
    DATA_ENTRY = "data_entry"

    ALL = frozenset([SUPERADMIN, ADMIN, MANAGEMENT, DATA_ENTRY])


class User(Base):
    """
    Локальная таблица пользователей.
    Creates the user with: passlib bcrypt hashing (12 rounds by default).
    """
    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint(
            f"role IN ('{UserRoleEnum.SUPERADMIN}','{UserRoleEnum.ADMIN}',"
            f"'{UserRoleEnum.MANAGEMENT}','{UserRoleEnum.DATA_ENTRY}')",
            name="ck_user_role",
        ),
        Index("ix_users_email_active", "email", "is_active"),
        Index("ix_users_org_role",      "org_id", "role"),
    )

    # ── Identity ──────────────────────────────────────────────────────────
    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.uuid_generate_v4(),
    )
    email: Mapped[str] = mapped_column(
        String(255), unique=True, nullable=False, index=True
    )
    password_hash: Mapped[str] = mapped_column(
        String(255),   # bcrypt produces 60-char strings but leave headroom for argon2 migration
        nullable=False,
    )

    # ── Profile ───────────────────────────────────────────────────────────
    full_name: Mapped[str] = mapped_column(String(200), nullable=False)
    phone: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)

    # ── RBAC ──────────────────────────────────────────────────────────────
    role: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default=UserRoleEnum.DATA_ENTRY,
    )
    org_id: Mapped[Optional[UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Organisation for data_entry users; NULL for admin/superadmin",
    )

    # ── Account state ─────────────────────────────────────────────────────
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true", index=True
    )
    must_change_password: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false",
        comment="True = force password change on next login",
    )

    # ── Security: brute-force protection ──────────────────────────────────
    failed_login_attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    locked_until: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Account locked until this timestamp (brute-force protection)",
    )
    last_login_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_login_ip: Mapped[Optional[str]] = mapped_column(String(45), nullable=True)

    # ── Password history (for rotation policy) ────────────────────────────
    password_changed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── Timestamps ────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )
    created_by: Mapped[Optional[UUID]] = mapped_column(
        PG_UUID(as_uuid=True), nullable=True,
        comment="UUID of the admin who created this user (NULL for bootstrap)",
    )

    # Soft delete
    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True, index=True
    )

    # ── Relationships (lazy="noload" for async safety) ────────────────────
    organization = relationship(
        "Organization",
        foreign_keys=[org_id],
        lazy="noload",
    )

    # ── Helpers ───────────────────────────────────────────────────────────
    @property
    def is_locked(self) -> bool:
        if not self.locked_until:
            return False
        return self.locked_until > datetime.now(self.locked_until.tzinfo)

    @property
    def can_login(self) -> bool:
        return self.is_active and not self.is_locked and not self.deleted_at


class RefreshToken(Base):
    """
    Server-side refresh token store.
    We store refresh tokens as bcrypt hashes so a DB leak does not expose them.
    A user has many refresh tokens (one per device / browser session).
    """
    __tablename__ = "refresh_tokens"
    __table_args__ = (
        Index("ix_refresh_user_active", "user_id", "revoked_at"),
    )

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.uuid_generate_v4(),
    )
    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    token_hash: Mapped[str] = mapped_column(
        String(255), nullable=False, unique=True
    )
    device_info: Mapped[Optional[str]] = mapped_column(
        String(500), nullable=True,
        comment="User-Agent string — helps users identify sessions to revoke",
    )
    ip_address: Mapped[Optional[str]] = mapped_column(String(45), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )
    revoked_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="Set on logout or when rotated by a fresh refresh",
    )
    last_used_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
